name: BayTech News
favicon: null
layout_spectrum: 0.3731
typography_spectrum: 0.24964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71078090-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6435382526833564
  lightness: 0.27264733146876097
  saturation: 0.2040389971807599
  rhythmicContrast: 0.22976443613879383
purpose: []
