name: BayTech News
favicon: null
layout_spectrum: 0.14618
typography_spectrum: 0.60527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71078090-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a498d'
    - '#0a194f'
    - '#2186c3'
    - '#bcf2ff'
    - '#8ac7dd'
  brandStrength: 0
  lightness: 0.27264733146876097
  saturation: 0.5
  rhythmicContrast: 0.22976443613879383
purpose: []
