name: BayTech News
favicon: null
layout_spectrum: 0.30875
typography_spectrum: 0.60527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71078090-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#337ca9'
    - '#57a2cc'
    - '#b5daf5'
    - '#e5ffff'
    - '#cfe9ef'
  brandStrength: 0
  lightness: 0.27264733146876097
  saturation: 0.5
  rhythmicContrast: 0.22976443613879383
purpose: []
